#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox"
STYLE="myTheme"
RASI="~/.config/hypr/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
