#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox"
STYLE="myTheme"
RASI="~/.config/hypr/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-theme "~/.config/hypr/rofi/launcher.rasi"
